services:
  postgres:
    image: postgres:16-alpine
    container_name: archiq-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ervishal
      POSTGRES_PASSWORD: archiq763
      POSTGRES_DB: archiq
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - archiq-dev

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      # target: development
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - archiq-dev
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: archiq-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - archiq-dev

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq-node
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=ervishal
      - RABBITMQ_DEFAULT_PASS=archiq763
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - archiq-dev

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - archiq-dev

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - archiq-dev

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  grafana_data:

networks:
  archiq-dev:
    driver: bridge
