spring.application.name=arkit


spring.datasource.url=jdbc:postgresql://localhost:5432/arkit
spring.datasource.username=ervishal
spring.datasource.password=ervishal763


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration