name: arkit
services:
  api:
    image: ghcr.io/ervishalpathak7/arkit.ai:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres.vzklrxaaaqjpfnqqvivr
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
