name: arkit
services:
  api:
    image: ghcr.io/ervishalpathak7/arkit.ai:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/arkit
      SPRING_DATASOURCE_USERNAME: arkit
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
