spring.application.name=api
spring.jackson.mapper.accept-case-insensitive-enums=true
llm.model=claude-haiku-5-5
llm.api-key=${ANTHROPIC_API_KEY:dummyfortesting}
logging.level.com.arkit=DEBUG
spring.flyway.schemas=arkit
spring.flyway.default-schema=arkit
spring.jpa.properties.hibernate.default_schema=arkit
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.vzklrxaaaqjpfnqqvivr
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
ratelimit.max-request=4
spring.jpa.open-in-view=false
